name: 编译并推送阿里云

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 02:00 UTC（北京时间 10:00）
  workflow_dispatch:      # 手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 启用 QEMU（让宿主机能模拟 arm64）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. 启用 buildx（多平台必备）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录阿里云
      - name: 登录阿里云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: crpi-f9fdchfskf2rzokg.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 构建并推送
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            crpi-f9fdchfskf2rzokg.cn-hangzhou.personal.cr.aliyuncs.com/zhouk/caddy-alidns:latest
            crpi-f9fdchfskf2rzokg.cn-hangzhou.personal.cr.aliyuncs.com/zhouk/caddy-alidns:${{ github.run_number }}
